# https://taskfile.dev

version: '3'

tasks:

  build-runtime-debug:
    dir: internal/runtime
    internal: true
    cmds:
      - npx esbuild desktop/main.js --bundle --sourcemap=inline --outfile=runtime_debug_desktop_{{.PLATFORM}}.js --define:DEBUG=true --define:WINDOWS={{.WINDOWS}} --define:DARWIN={{.DARWIN}} --define:LINUX={{.LINUX}} --define:PLATFORM={{.PLATFORM}}

  build-runtime-debug-windows:
    cmds:
      - task: build-runtime-debug
        vars:
          WINDOWS: true
          DARWIN: false
          LINUX: false
          PLATFORM: windows

  build-runtime-debug-linux:
    cmds:
      - task: build-runtime-debug
        vars:
          WINDOWS: false
          DARWIN: false
          LINUX: true
          PLATFORM: linux

  build-runtime-debug-darwin:
    cmds:
      - task: build-runtime-debug
        vars:
          WINDOWS: false
          DARWIN: true
          LINUX: false
          PLATFORM: darwin

  build-runtime-production:
    dir: internal/runtime
    internal: true
    cmds:
      - npx esbuild desktop/main.js --bundle --minify --outfile=runtime_production_desktop_{{.PLATFORM}}.js --define:DEBUG=true --define:WINDOWS={{.WINDOWS}} --define:DARWIN={{.DARWIN}} --define:LINUX={{.LINUX}} --define:PLATFORM={{.PLATFORM}}

  build-runtime-production-windows:
    cmds:
      - task: build-runtime-production
        vars:
          WINDOWS: true
          DARWIN: false
          LINUX: false
          PLATFORM: windows

  build-runtime-production-linux:
    cmds:
      - task: build-runtime-production
        vars:
          WINDOWS: false
          DARWIN: false
          LINUX: true
          PLATFORM: linux

  build-runtime-production-darwin:
    cmds:
      - task: build-runtime-production
        vars:
          WINDOWS: false
          DARWIN: true
          LINUX: false
          PLATFORM: darwin

  install-runtime-dev-deps:
    dir: internal/runtime/dev
    internal: true
    sources:
      - package.json
    cmds:
      - npm install


  install-runtime-deps:
    dir: internal/runtime
    internal: true
    sources:
      - package.json
    cmds:
      - npm install

  build-runtime-dev:
    dir: internal/runtime/dev
    deps:
        - install-runtime-dev-deps
    sources:
      - ./*.js
    generates:
      - ../ipc_websocket.js
    cmds:
      - node build.js

  build-runtime-ipc:
    dir: internal/runtime
    deps:
        - install-runtime-dev-deps
    sources:
      - ./desktop/ipc.js
    generates:
      - ipc.js
    cmds:
      - npx esbuild desktop/ipc.js --bundle --minify --outfile=ipc.js

  test-runtime:
    dir: internal/runtime
    cmds:
      - npx vitest

  build-runtime-all:
    dir: internal/runtime
    deps:
      - build-runtime-production-darwin
      - build-runtime-production-windows
      - build-runtime-production-linux
      - build-runtime-debug-darwin
      - build-runtime-debug-windows
      - build-runtime-debug-linux
      - build-runtime-dev
      - build-runtime-ipc
    cmds:
      - task: test-runtime

  build-runtime:
    dir: internal/runtime
    deps:
      - install-runtime-deps
    cmds:
      - task: build-runtime-all
